### ISSUE TITLE
merge_records fails hard if some value of a list is null

### ISSUE THREAD

**Issue by rvalyi** [OCA/openupgradelib#138]
example:
```
2019-02-08 23:25:15,944 144 ERROR openupgrade-to-11 odoo.modules.registry: Failed to load registry                                                                                                           
Traceback (most recent call last):                                                                                                                                                                           
  File "/odoo/src/odoo/modules/registry.py", line 85, in new                                                                                                                                                 
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)                                                                                                                               
  File "/odoo/src/odoo/modules/loading.py", line 463, in load_modules                                                                                                                                        
    migrations.migrate_module(package, 'end')                                                                                                                                                                
  File "/odoo/src/odoo/modules/migration.py", line 187, in migrate_module                                                                                                                                    
    migrate(self.cr, installed_version)                                                                                                                                                                      
  File "/src/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function                                                                                                                   
    if use_env2 else cr, version)                                                                                                                                                                            
  File "/odoo/src/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate                                                                                                                    
    merge_quants(env)                                                                                                                                                                                        
  File "/odoo/src/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants                                                                                                               
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,                                                                                                                                       
  File "/src/openupgradelib/openupgradelib/openupgrade_merge_records.py", line 505, in merge_records
    _adjust_merged_values_orm(*args2)
  File "/src/openupgradelib/openupgradelib/openupgrade_merge_records.py", line 354, in _adjust_merged_values_orm
    vals[field.name] = min(l)
TypeError: unorderable types: bool() < str()
2019-02-08 23:25:15,945 144 CRITICAL openupgrade-to-11 odoo.service.server: Failed to initialize database `openupgrade-to-11`.
Traceback (most recent call last):
  File "/odoo/src/odoo/service/server.py", line 932, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo/src/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/src/odoo/modules/loading.py", line 463, in load_modules
    migrations.migrate_module(package, 'end')
  File "/odoo/src/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/src/openupgradelib/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/src/addons/stock/migrations/11.0.1.1/end-migration.py", line 31, in migrate
    merge_quants(env)
  File "/odoo/src/addons/stock/migrations/11.0.1.1/end-migration.py", line 25, in merge_quants
    env, 'stock.quant', quants[1:].ids, quants[0].id, QUANT_MERGE_OPS,
  File "/src/openupgradelib/openupgradelib/openupgrade_merge_records.py", line 505, in merge_records
    _adjust_merged_values_orm(*args2)
  File "/src/openupgradelib/openupgradelib/openupgrade_merge_records.py", line 354, in _adjust_merged_values_orm
    vals[field.name] = min(l)
TypeError: unorderable types: bool() < str()
```

probably some heuristics, like filter null date/datetime from the list could help. The same may happen with the comparisons of other types...

**Comment by pedrobaeza** [comment]
Can you specify in which field and with which values this is happening? On standard, this is not possible, but might be with custom fields in `stock.quant` model.

**Comment by rvalyi** [comment]
busy with some other stuff now, but I will print the field and object names

**Comment by pedrobaeza** [comment]
Yes, the field type is the data to have mainly for knowing what happens.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by zaoral** [comment]
I confirm this error.

One way to reproduce it is by trying to merge task stages model (project.task.type) records 
If you try to merge stages that have description field empty then this error appears.

The occurs when we try to merge records that have empty text fields.
I have test it and this is solved with fix  https://github.com/OCA/openupgradelib/pull/139

Please consider this PR and let me know if need to add something else to the PR

Best Regards
