### ISSUE TITLE
module 'odoo.tools' has no attribute 'yaml_import' 

### ISSUE THREAD

**Issue by rossigee** [OCA/openupgradelib#153]
Using latest OCA/OpenUpgrade `12.0` branch, and `pip install openupgradelib>=2.0.0
`...

```
2019-06-25 04:00:46,369 23631 CRITICAL ? odoo.modules.module: Couldn't load module base 
2019-06-25 04:00:46,369 23631 CRITICAL ? odoo.modules.module: module 'odoo.tools' has no attribute 'yaml_import' 
2019-06-25 04:00:46,370 23631 ERROR ? odoo.service.server: Failed to load server-wide module `base`. 
Traceback (most recent call last):
  File "/odoo/OpenUpgrade/odoo/service/server.py", line 1063, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/odoo/OpenUpgrade/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/odoo/OpenUpgrade/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 5, in <module>
  File "/odoo/OpenUpgrade/odoo/addons/base/models/__init__.py", line 7, in <module>
    from . import ir_model
  File "/odoo/OpenUpgrade/odoo/addons/base/models/ir_model.py", line 17, in <module>
    from openupgradelib import openupgrade
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 84, in <module>
    yaml_import = tools.yaml_import
```

I can't see the `yaml_import` function defined in either OCA/OpenUpgrade or upstream odoo `12.0` source trees. Where is this function defined?

**Comment by rossigee** [comment]
Commenting out all references to `yaml_import`, the upgrade process proceeds much further, but then hits another `AttributeError` related to the `openupgradelib` library...

```
2019-06-25 04:21:06,964 23640 INFO bksc odoo.modules.migration: module base: Running migration [12.0.1.3>] post-migration 
2019-06-25 04:21:06,966 23640 INFO bksc OpenUpgrade: base: post-migration script called with version 11.0.1.3 
2019-06-25 04:21:06,966 23640 INFO bksc odoo.models: Computing parent_path for table ir_ui_menu... 
2019-06-25 04:21:06,989 23640 INFO bksc odoo.models: Computing parent_path for table res_partner_category... 
2019-06-25 04:21:06,991 23640 ERROR bksc OpenUpgrade: base: error in migration script base/migrations/12.0.1.3/post-migration.py: module 'openupgradelib.openupgrade' has no attribute 'chunked' 
2019-06-25 04:21:06,991 23640 ERROR bksc OpenUpgrade: module 'openupgradelib.openupgrade' has no attribute 'chunked' 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/odoo/OpenUpgrade/odoo/addons/base/migrations/12.0.1.3/post-migration.py", line 39, in migrate
    generate_thumbnails(env)
  File "/odoo/OpenUpgrade/odoo/addons/base/migrations/12.0.1.3/post-migration.py", line 9, in generate_thumbnails
    for chunk in openupgrade.chunked(
AttributeError: module 'openupgradelib.openupgrade' has no attribute 'chunked'
```

I get the feeling I'm using the wrong version of something?!?

**Comment by rossigee** [comment]
OK, so 'pip uninstall openupgradelib` and `pip install git+https://github.com/OCA/openupgradelib` appears to fix the above problems and allow the upgrade to run to completion.

Perhaps a new release of openupgradelib is overdue?

**Comment by pedrobaeza** [comment]
Not really. The documentation is clear about how to install the library:

https://doc.therp.nl/openupgrade/migration_details.html#general-tips

**Comment by lmignon** [comment]
@StefanRijnhart Is-it possible to publish a new release on pypi PLZ. It's very annoying than an old one sill exists on pypi and not the last one. I don't see any motivation to not have this python lib released on pypi.
Thank you in advance.

**Comment by pedrobaeza** [comment]
Publishing in PyPI is not working: https://travis-ci.org/OCA/openupgradelib/builds/585505577#L9967

See some discussion in https://github.com/OCA/openupgradelib/pull/176#issuecomment-533248967

If you want to fix it, please propose the patch for making it work. Meanwhile, I find it as something not needed, having the pip install from sources method.

**Comment by lmignon** [comment]
Thank you for the link @pedrobaeza
