### ISSUE TITLE
SQL Error when try to upgrade from 7.0 to 8.0

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/openupgradelib#192]
When I launch an upgrade from 7.0 to 8.0 with `OpenUpgrade` `migration.py` script, `openupgradelib` rise an error:

```python
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 941, in prelo
ad_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 420, in load
_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 312, in load
_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip
_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 208, in load
_module_graph
    migrations.migrate_module(package, 'post')
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/migration.py", line 179, in mi
grate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 1495,
 in wrapped_function
    if use_env2 else cr, version)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", l
ine 1150, in migrate
    migrate_stock_qty(cr, registry)
  File "/var/tmp/openupgrade/8.0/addons/stock/migrations/8.0.1.1/post-migration.py", l
ine 950, in migrate_stock_qty
    create_index.format(table=table, col=col),
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 979, 
in logged_query
    cr.execute(query, args)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: ERREUR:  erreur de syntaxe sur ou près de « NOT »
LIGNE 2 :         CREATE INDEX IF NOT EXISTS stock_pack_operation_loca...
```

**Comment by pedrobaeza** [comment]
This is not something of openupgradelib, nor even openupgrade. You should use a higher postgres version.
