### ISSUE TITLE
Importation of psycopg2.sql can cause broblem with old installation of Odoo

### ISSUE THREAD

**Issue by sebastienhasa** [OCA/openupgradelib#193]
I run a migration from Odoo 8 to Odoo 9 with openupgrade inside the
Official (but no more supported) Odoo docker image 8.0.

When I run the `migrate.py` script, I got this error:
```python
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp-server", line 2, in <module>
    import openerp
  File "/var/tmp/openupgrade/9.0/server/openerp/__init__.py", line 64, in <module>
    import modules
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 28, in <module>
    from openerp.openupgrade import openupgrade_loading, deferred_90
  File "/var/tmp/openupgrade/9.0/server/openerp/openupgrade/deferred_90.py", line 37, in <module>
    from openupgradelib import openupgrade, openupgrade_90, openupgrade_tools
  File "/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py", line 57, in <module>
    from psycopg2 import sql
ImportError: cannot import name sql
```

Apparently, `openupgradelib` assumes that you run a recent version of
`psycopg2`, which it's not the case in environment with old version of
Odoo. This can cause problem when you do migration from old Odoo.

**Comment by pedrobaeza** [comment]
I think you can override the version of psycopg2 library in the Docker. There's no reason for sticking to an old version compatibility that it's not needed, and there's no way back of removing that useful feature.

**Comment by sebastienhasa** [comment]
Installing psycopg2 from pypi.org fix the problem, in condition that your GNU/Linux is not too old to let you install gcc and libpg-dev from its repo.
