### ISSUE TITLE
pip downloaded outdated version

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#2]
If I make: `sudo pip install openupgradelib`, I get:
```
Downloading/unpacking openupgradelib
  Downloading openupgradelib-0.1.0.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/tmp/pip_build_root/openupgradelib/setup.py) egg_info for package openupgradelib
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/openupgradelib/setup.py", line 17, in <module>
        with open('requirements.txt') as requirements_file:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/openupgradelib/setup.py", line 17, in <module>

    with open('requirements.txt') as requirements_file:

IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

And that's because it's downloading version 0.1.0 instead of version 0.1.2.

**Comment by bwrsandman** [comment]
It's because for some reason `openupgradelib-0.1.0.tar.gz` is up but not `openupgradelib-0.1.2.tar.gz` Something went wrong during the upload. Looking into this.

**Comment by bwrsandman** [comment]
Fixed. MANIFEST.in was not including requirements.txt

**Comment by pedrobaeza** [comment]
Thanks!
