### ISSUE TITLE
PyPI stuff just broke install on Python 2.7

### ISSUE THREAD

**Issue by rvalyi** [OCA/openupgradelib#248]
Hello when doing an openupgradelib install of the master branch for a v8 to v9 migration I get:

```
Collecting git+https://github.com/OCA/openupgradelib.git@master (from -r /odoo/oca_requirements.txt (line 24))                                                                                               
  Cloning https://github.com/OCA/openupgradelib.git (to revision master) to /tmp/pip-req-build-PGMtXy                                                                                                        
  Running command git clone -q https://github.com/OCA/openupgradelib.git /tmp/pip-req-build-PGMtXy                                                                                                           
    ERROR: Command errored out with exit status 1:                                                                                                             
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-PGMtXy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-PGMtXy/setup.py'"'"';f=getattr(tokenize, '"$
"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-PGMtXy/pip-egg-info
         cwd: /tmp/pip-req-build-PGMtXy/                                                                                                                              
    Complete output (16 lines):                    
    Traceback (most recent call last):                                                                                                                            
      File "<string>", line 1, in <module>                                                                                                              
      File "/tmp/pip-req-build-PGMtXy/setup.py", line 5, in <module>                                                                                  
        import openupgradelib                                      
      File "openupgradelib/__init__.py", line 15, in <module>                                                                               
        from importlib_metadata import version, PackageNotFoundError                                                                                                                                       
      File "/usr/local/lib/python2.7/dist-packages/importlib_metadata/__init__.py", line 9, in <module>                                                                          
        import zipp                                                                                                                                                    
      File "/usr/local/lib/python2.7/dist-packages/zipp.py", line 12, in <module>                                                                                    
        import more_itertools                                                                                                                                        
      File "/usr/local/lib/python2.7/dist-packages/more_itertools/__init__.py", line 1, in <module>                                                                  
        from .more import *  # noqa                                                                                                                                                           
      File "/usr/local/lib/python2.7/dist-packages/more_itertools/more.py", line 460                                                                                                                   
        yield from iterable                                                                                                                                                                   
                 ^                                                                                                                                                                                         
    SyntaxError: invalid syntax                                                                                                                                                                        
    ----------------------------------------                                                                   
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.      
```

This was with `git+https://github.com/OCA/openupgradelib.git@master` in my oca_requirements.txt file (rev https://github.com/OCA/openupgradelib/commit/5b374a2e21fa18ca25c88b34a07d308a970be0d7 at this time).

bissecting further I could nail the regression to this exact PyPI commit from @sbidoul :
https://github.com/OCA/openupgradelib/commit/77513de21fb87ed367cb26b4bbe45faa78da5bba

Indeed taking the previous revision works:
`pip install git+https://github.com/OCA/openupgradelib.git@ed01555b8ae20f66b3af178c8ecaf6edd110ce75#egg=openupgradelib`

But `pip install git+https://github.com/OCA/openupgradelib.git@77513de21fb87ed367cb26b4bbe45faa78da5bba#egg=openupgradelib` fails with the same stack trace I just mentioned.

**Comment by sbidoul** [comment]
@rvalyi the stack trace shows the error comes from `from importlib_metadata import version, PackageNotFoundError`, which in turn import zipp which in turn more_itertools which uses yield from which is not python2 compatible indeed.

But, when I pip install the latest importlib_metadata in a fresh python2 venv it does not occur.

And I can `pip install git+https://github.com/OCA/openupgradelib.git@master` in a fresh python2 virtualenv without problem.

So I suspect you have an old and/or broken importlib_metadata or zip or more_intertools in your environment.

**Comment by rvalyi** [comment]
this is using the C2C Debian Jessie image: https://github.com/camptocamp/docker-odoo-project/blob/master/9.0/Dockerfile
bad news, even updating it right now doesn't make it work either.

We might close the issue as it may work on other more modern 2.7 configurations, but for people relying heavily on that C2C image (like us) that could become a timebomb. Cause it was OK for me taking the revision from 3 days ago, in 2 years OpenUpgrade scripts might rely on a much newer openupgrtadelib and people may be stuck. What do you think?

**Comment by rvalyi** [comment]
so for everyone struggling with that one, for me I had to do the following before trying to install openupgradelib on a legacy Python 2.7 (Debian Jessie based image) to run OpenUpgrade migrations:

```
pip install git+https://github.com/jaraco/zipp.git@v1.0.0
pip install -U git+https://github.com/python/importlib_metadata.git@maint/2.x
```

So a recent importlib_metadata would not do the job as it required Python 3.x, and even just trying to install it from the maint/2.x branch would also fail with the zipp dependency unless we pin it to a Python 2.7 version like with the v1.0.0 tag. Happy legacy migration!
After that things worked as expected.
