### ISSUE TITLE
Travis CI broken

### ISSUE THREAD

**Issue by legalsylvain** [OCA/openupgradelib#321]
Hi @OCA/openupgrade-maintainers.

It looks that the CI is currently broken, preventing new contributions.
- https://github.com/OCA/openupgradelib/pull/318. (documentation PR)
- https://github.com/OCA/openupgradelib/pull/319 (new functions PR)
- https://github.com/OCA/openupgradelib/pull/320 (trivial PR to test the CI).

Ref Log : https://app.travis-ci.com/github/OCA/openupgradelib/builds/262918163#L486

<details><summary>See Log</summary>

```
$ egrep -v "(openupgradelib)|(psycopg2)" requirements.txt | pip install -q -r /dev/stdin

  ERROR: Command errored out with exit status 1:


   command: /home/travis/virtualenv/python3.6.9/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ptg_61i7/jcconv_6145550156584cd98206523348f451d5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ptg_61i7/jcconv_6145550156584cd98206523348f451d5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7xaylr7g

       cwd: /tmp/pip-install-ptg_61i7/jcconv_6145550156584cd98206523348f451d5/

  Complete output (6 lines):

  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "/tmp/pip-install-ptg_61i7/jcconv_6145550156584cd98206523348f451d5/setup.py", line 17

      print "unit tests have failed!"

                                    ^

  SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unit tests have failed!")?

  ----------------------------------------

WARNING: Discarding https://files.pythonhosted.org/packages/dd/5b/55d6dd385e8584c6750864ddec8d5ff82a295b37ac68344febc9e923bf99/jcconv-0.2.3.tar.gz#sha256=e3bd59d3fb129b952f84c66e6187abddb88cc7c2b3c83b12685a3256fd3b5e54 (from https://pypi.org/simple/jcconv/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: Could not find a version that satisfies the requirement jcconv==0.2.3 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.2, 0.2.3)

ERROR: No matching distribution found for jcconv==0.2.3
```
</details>

Around that topic : 
- an idea of @pedrobaeza to switch to github action https://github.com/OCA/openupgradelib/pull/317#issuecomment-1427921845
- The last PR that worked was https://github.com/OCA/openupgradelib/pull/317. (Fev, 13, 2023)

Kind regards.

**Comment by hbrunn** [comment]
fixed in https://github.com/OCA/openupgradelib/pull/322
