### ISSUE TITLE
Crash in error logging with UTF-8 message

### ISSUE THREAD

**Issue by hmartinet** [OCA/openupgradelib#90]
str(e) will crash if there is special characters in the exception message (because I am in fr_CH.UTF8 with my user on my system I think). Then the error that occurs is not displayed in the log. I will try to run the process with another temporary session locale but this is not very clean.

Traceback (most recent call last):
  File "/[…]/9.0/server/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/[…]/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/[…]/9.0/server/openerp/modules/loading.py", line 342, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)
  File "/[…]/9.0/server/openerp/modules/loading.py", line 189, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/[…]/9.0/server/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/[…]/openupgradelib/openupgradelib/openupgrade.py", line 1391, in wrapped_function
    message = str(e)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 69: ordinal not in range(128)

**Comment by pedrobaeza** [comment]
Till now, I don't have any problem with that. Any way, please propose a PR if you think about other formula

**Comment by hmartinet** [comment]
Yes if I found something better which will for me, I will purpose a PR.

**Comment by hmartinet** [comment]
https://github.com/OCA/openupgradelib/pull/91
